// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smp.services.invoice.core;

namespace smp.services.invoice.portal.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    [Migration("20210309072554_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("smp.services.invoice.core.Invoice.Entities.InvoiceDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Fphxz")
                        .HasColumnType("text");

                    b.Property<string>("Goodsname")
                        .HasColumnType("text");

                    b.Property<string>("Hsbz")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceOrderId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Kce")
                        .HasColumnType("text");

                    b.Property<string>("Lslbs")
                        .HasColumnType("text");

                    b.Property<string>("Num")
                        .HasColumnType("text");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<string>("Spbm")
                        .HasColumnType("text");

                    b.Property<string>("Spec")
                        .HasColumnType("text");

                    b.Property<string>("Tax")
                        .HasColumnType("text");

                    b.Property<string>("Taxamt")
                        .HasColumnType("text");

                    b.Property<string>("Taxfreeamt")
                        .HasColumnType("text");

                    b.Property<string>("Taxrate")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<string>("Yhzcbs")
                        .HasColumnType("text");

                    b.Property<string>("Zsbm")
                        .HasColumnType("text");

                    b.Property<string>("Zzstsgl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceOrderId");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("smp.services.invoice.core.Invoice.Entities.InvoiceOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BillInfoNo")
                        .HasColumnType("text");

                    b.Property<string>("BuyerName")
                        .HasColumnType("text");

                    b.Property<string>("CallbackUrl")
                        .HasColumnType("text");

                    b.Property<string>("Checker")
                        .HasColumnType("text");

                    b.Property<string>("Clerk")
                        .HasColumnType("text");

                    b.Property<string>("Clerkid")
                        .HasColumnType("text");

                    b.Property<byte[]>("Client")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Cpybz")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Deptid")
                        .HasColumnType("text");

                    b.Property<string>("Dkbz")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Fpdm")
                        .HasColumnType("text");

                    b.Property<string>("Fphm")
                        .HasColumnType("text");

                    b.Property<string>("Fpqqlsh")
                        .HasColumnType("text");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime");

                    b.Property<string>("InvoiceLine")
                        .HasColumnType("text");

                    b.Property<string>("KpType")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("OrderNo")
                        .HasColumnType("text");

                    b.Property<string>("OutOrderNo")
                        .HasColumnType("text");

                    b.Property<string>("Payee")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Qdbz")
                        .HasColumnType("text");

                    b.Property<string>("Qdxmmc")
                        .HasColumnType("text");

                    b.Property<string>("SaleAccount")
                        .HasColumnType("text");

                    b.Property<string>("SaleAddress")
                        .HasColumnType("text");

                    b.Property<string>("SalePhone")
                        .HasColumnType("text");

                    b.Property<string>("SaletaxNum")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StateMessage")
                        .HasColumnType("text");

                    b.Property<string>("Taxnum")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<string>("Tsfs")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InvoiceOrders");
                });

            modelBuilder.Entity("smp.services.invoice.core.Invoice.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("smp.services.invoice.core.Invoice.Entities.InvoiceOrder", "InvoiceOrder")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceOrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
