// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smp.services.invoice.core;

namespace smp.services.invoice.portal.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    partial class InvoiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("smp.services.invoice.core.Invoice.Entities.InvoiceDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Fphxz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Goodsname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hsbz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoiceOrderId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Kce")
                        .HasColumnType("text");

                    b.Property<string>("Lslbs")
                        .HasColumnType("text");

                    b.Property<string>("Num")
                        .HasColumnType("text");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<string>("Spbm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Spec")
                        .HasColumnType("text");

                    b.Property<string>("Tax")
                        .HasColumnType("text");

                    b.Property<string>("Taxamt")
                        .HasColumnType("text");

                    b.Property<string>("Taxfreeamt")
                        .HasColumnType("text");

                    b.Property<string>("Taxrate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<string>("Yhzcbs")
                        .HasColumnType("text");

                    b.Property<string>("Zsbm")
                        .HasColumnType("text");

                    b.Property<string>("Zzstsgl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceOrderId");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("smp.services.invoice.core.Invoice.Entities.InvoiceOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BillInfoNo")
                        .HasColumnType("text");

                    b.Property<string>("BuyerName")
                        .HasColumnType("text");

                    b.Property<string>("CallbackUrl")
                        .HasColumnType("text");

                    b.Property<string>("Checker")
                        .HasColumnType("text");

                    b.Property<string>("Clerk")
                        .HasColumnType("text");

                    b.Property<string>("Clerkid")
                        .HasColumnType("text");

                    b.Property<string>("Client")
                        .HasColumnType("text");

                    b.Property<string>("Cpybz")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Deptid")
                        .HasColumnType("text");

                    b.Property<string>("Dkbz")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Fpdm")
                        .HasColumnType("text");

                    b.Property<string>("Fphm")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceDate")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceLine")
                        .HasColumnType("text");

                    b.Property<int>("InvoiceType")
                        .HasColumnType("int");

                    b.Property<string>("KpType")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("OrderNo")
                        .HasColumnType("text");

                    b.Property<string>("OutOrderNo")
                        .HasColumnType("text");

                    b.Property<string>("Payee")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Qdbz")
                        .HasColumnType("text");

                    b.Property<string>("Qdxmmc")
                        .HasColumnType("text");

                    b.Property<string>("SaleAccount")
                        .HasColumnType("text");

                    b.Property<string>("SaleAddress")
                        .HasColumnType("text");

                    b.Property<string>("SalePhone")
                        .HasColumnType("text");

                    b.Property<string>("SaletaxNum")
                        .HasColumnType("text");

                    b.Property<string>("SerialNum")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StateMessage")
                        .HasColumnType("text");

                    b.Property<string>("Taxnum")
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.Property<string>("Tsfs")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InvoiceOrders");
                });

            modelBuilder.Entity("smp.services.invoice.core.Invoice.Entities.InvoiceOrderResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("InvoiceOrderId")
                        .HasColumnType("text");

                    b.Property<string>("c_address")
                        .HasColumnType("text");

                    b.Property<string>("c_bankAccount")
                        .HasColumnType("text");

                    b.Property<float>("c_bhsje")
                        .HasColumnType("float");

                    b.Property<string>("c_buyername")
                        .HasColumnType("text");

                    b.Property<string>("c_checker")
                        .HasColumnType("text");

                    b.Property<string>("c_clerk")
                        .HasColumnType("text");

                    b.Property<string>("c_clerkId")
                        .HasColumnType("text");

                    b.Property<string>("c_deptId")
                        .HasColumnType("text");

                    b.Property<string>("c_fpdm")
                        .HasColumnType("text");

                    b.Property<string>("c_fphm")
                        .HasColumnType("text");

                    b.Property<string>("c_fpqqlsh")
                        .HasColumnType("text");

                    b.Property<string>("c_hjje")
                        .HasColumnType("text");

                    b.Property<float>("c_hjse")
                        .HasColumnType("float");

                    b.Property<string>("c_imgUrls")
                        .HasColumnType("text");

                    b.Property<string>("c_invoice_line")
                        .HasColumnType("text");

                    b.Property<string>("c_invoiceid")
                        .HasColumnType("text");

                    b.Property<string>("c_jpg_url")
                        .HasColumnType("text");

                    b.Property<string>("c_jym")
                        .HasColumnType("text");

                    b.Property<long>("c_kprq")
                        .HasColumnType("bigint");

                    b.Property<string>("c_mail")
                        .HasColumnType("text");

                    b.Property<string>("c_msg")
                        .HasColumnType("text");

                    b.Property<string>("c_orderno")
                        .HasColumnType("text");

                    b.Property<string>("c_payee")
                        .HasColumnType("text");

                    b.Property<string>("c_phone")
                        .HasColumnType("text");

                    b.Property<int>("c_qdbz")
                        .HasColumnType("int");

                    b.Property<string>("c_qdxmmc")
                        .HasColumnType("text");

                    b.Property<string>("c_remark")
                        .HasColumnType("text");

                    b.Property<string>("c_resultmsg")
                        .HasColumnType("text");

                    b.Property<string>("c_saleName")
                        .HasColumnType("text");

                    b.Property<string>("c_salerAccount")
                        .HasColumnType("text");

                    b.Property<string>("c_salerAddress")
                        .HasColumnType("text");

                    b.Property<string>("c_salerTaxNum")
                        .HasColumnType("text");

                    b.Property<string>("c_salerTel")
                        .HasColumnType("text");

                    b.Property<string>("c_status")
                        .HasColumnType("text");

                    b.Property<string>("c_taxnum")
                        .HasColumnType("text");

                    b.Property<string>("c_telephone")
                        .HasColumnType("text");

                    b.Property<string>("c_url")
                        .HasColumnType("text");

                    b.Property<string>("c_yfpdm")
                        .HasColumnType("text");

                    b.Property<string>("c_yfphm")
                        .HasColumnType("text");

                    b.Property<string>("cipherText")
                        .HasColumnType("text");

                    b.Property<string>("extensionNumber")
                        .HasColumnType("text");

                    b.Property<string>("machineCode")
                        .HasColumnType("text");

                    b.Property<string>("productOilFlag")
                        .HasColumnType("text");

                    b.Property<string>("qrCode")
                        .HasColumnType("text");

                    b.Property<string>("terminalNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InvoiceOrderResults");
                });

            modelBuilder.Entity("smp.services.invoice.core.Invoice.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("smp.services.invoice.core.Invoice.Entities.InvoiceOrder", "InvoiceOrder")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceOrderId");
                });
#pragma warning restore 612, 618
        }
    }
}
